backend:
  name: git-gateway
  branch: master

media_folder: static/img # Folder where user uploaded files should go
public_folder: /img

search: false

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: '-'

collections:
  - name: authors
    identifier_field: name
    label: Authors
    folder: content/authors
    create: true
    slug: '{{id}}'
    fields:
      - { label: ID, name: id, widget: string }
      - { label: Name, name: name, widget: string }
      - {
          label: Avatar,
          name: avatar,
          widget: image,
          choose_url: true,
          allow_multiple: false,
          required: false
        }
      - { label: Occupation, name: occupation, widget: string, required: false }
      - { label: Company, name: company, widget: string, required: false }
      - { label: Email, name: email, widget: string, required: false }
      - { label: Twitter, name: twitter, widget: string, required: false }
      - { label: LinkedIn, name: linkedin, widget: string, required: false }
      - { label: GitHub, name: github, widget: string, required: false }
  - name: posts # Used in routes, e.g., /admin/collections/blog
    identifier_field: title
    label: Posts # Used in the UI
    folder: content/posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - {
          label: 'Publish Date',
          name: date,
          widget: datetime,
          default: '',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'LLL'
        }
      - { label: Draft, name: draft, widget: boolean, default: true, required: false }
      - { label: Summary, name: summary, widget: string, required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          choose_url: true,
          allow_multiple: false,
          required: false
        }
      - { label: Body, name: 'body', widget: 'markdown' }
  - name: projects # Used in routes, e.g., /admin/collections/blog
    identifier_field: title
    label: Projects # Used in the UI
    folder: content/projects # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - { label: 'Date', name: date, widget: datet, default: '', format: 'YYYY-MM-DD' }
      - { label: Draft, name: draft, widget: boolean, default: true, required: false }
      - { label: Description, name: description, widget: string, required: false }
      - { label: Link, name: link, widget: string, required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          choose_url: true,
          allow_multiple: false,
          required: false
        }
      - {
          label: Type,
          name: type,
          widget: select,
          options:
            [
              'company',
              'interview',
              'music video',
              'production',
              'project',
              'other - aware',
              'other - design',
              'other - paper',
              'other - panel',
              'other - reportage',
              'other - video'
            ]
        }
      - { label: Body, name: 'body', widget: 'markdown' }
